name: snapinv_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  google_fonts: ^6.2.1
  camera: ^0.11.0+2
  image_picker: ^0.8.7+4
  http: ^1.2.2
  barcode_scan2: ^4.3.3
  path_provider: ^2.1.5
  shared_preferences: ^2.3.5
  collection: ^1.18.0
  fl_chart: ^0.70.2
  mobile_scanner: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true